apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  storageClassName: ebs-sc-01
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
